/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AnyPreferenceSpecifier =
  | PSGroupSpecifier
  | PSTextFieldSpecifier
  | PSToggleSwitchSpecifier
  | PSSliderSpecifier
  | PSChildPaneSpecifier
  | PSTitleValueSpecifier
  | PSMultiValueSpecifier
  | PSRadioGroupSpecifier;
export type UserInterfaceIdiom = "Pad" | "Phone";
export type ScalarType = string | number | boolean;

/**
 * https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/RevisionHistory.html#//apple_ref/doc/uid/TP40007071-CH2-SW1
 */
export interface SettingsPlist {
  /**
   * The name of the strings file associated with this schema file. A copy of this file (with appropriate localized strings) should be located in each of your bundle’s language-specific project directories. If you do not include this key, the strings in this schema file are not localized. For information on creating strings files, see Internationalization and Localization Guide.
   */
  StringsTable?: string;
  /**
   * The app group identifier to use for storing preference values. Specify this key when you want preferences to be stored in a container other than the one used by your iOS app. For example, specify this key when creating a WatchKit settings bundle so that the WatchKit extension can access the preferences. Enable the App Groups capability for each executable that needs to access the shared preferences. The group you select should match the value of this key. To access preferences stored in the group, pass the value of this key to the initWithSuiteName: method of your NSUserDefaults object. This key is supported in iOS 8.2 and later.
   */
  ApplicationGroupContainerIdentifier?: string;
  /**
   * An array of dictionaries, each of which contains the data for a single preference element. The order of the elements in the array defines the order that they are displayed on the screen.
   */
  PreferenceSpecifiers: AnyPreferenceSpecifier[];
}
/**
 * This type defines a group element, which is a way to visually group preferences on a page. This element should be placed in front of the preferences associated with the group. You can assign a title to the group or omit the key to display a gap between preferences. https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSGroupSpecifier.html#//apple_ref/doc/uid/TP40007009-SW1
 */
export interface PSGroupSpecifier {
  Type: "PSGroupSpecifier";
  /**
   * The title of the group. If you do not specify this key, a gap is inserted between preferences. The value of this key is localizable.
   */
  Title?: string;
  /**
   * Additional text to display below the group box. Providing a footer is optional. The value of this key is localizable. On tvOS, the additional text is limited to 5 lines.
   */
  FooterText?: string;
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
/**
 * https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSTextFieldSpecifier.html#//apple_ref/doc/uid/TP40007011-SW1
 */
export interface PSTextFieldSpecifier {
  Type: "PSTextFieldSpecifier";
  /**
   * The string displayed to the left of the text field's value. This string is drawn left aligned and in bold face. If you omit this key, the editable text field spans the width of the row.
   */
  Title?: string;
  /**
   * The preference key with which to associate the value. This is the string you use this to retrieve the preference value in your code.
   */
  Key: string;
  /**
   * The default value for the preference key. This value is returned when the specified preferences key (represented by the `Key` entry) is not present in the preferences database. If this key is not present, an empty string is associated with the key.
   */
  DefaultValue?: string;
  /**
   * If `true`, the text field is a password-entry text field, which replaces the typed text with bullet characters. If `false`, the text field is a standard text field that displays the typed text. If this key is not present, the default is `false`.
   */
  IsSecure?: boolean;
  /**
   * The type of keyboard to display to the user.
   */
  KeyboardType?: "Alphabet" | "NumbersAndPunctuation" | "NumberPad" | "URL" | "EmailAddress";
  /**
   * The auto-capitalization style to apply to typed text.
   */
  AutocapitalizationType?: "None" | "Sentences" | "Words" | "AllCharacters";
  /**
   * The auto-correction style to apply when typing.
   */
  AutocorrectionType?: "Default" | "No" | "Yes";
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
/**
 * This element displays an ON/OFF button that can be toggled by the user. https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSToggleSwitchSpecifier.html#//apple_ref/doc/uid/TP40007012-SW1
 */
export interface PSToggleSwitchSpecifier {
  Type: "PSToggleSwitchSpecifier";
  /**
   * The string displayed to the left of the switch.
   */
  Title: string;
  /**
   * The preference key identifying the value. This is the string you use this to retrieve the preference value from the defaults database.
   */
  Key: string;
  /**
   * The default value for the preference key. This value is returned when the specified preferences key (represented by the `Key` entry) is not present in the defaults database.
   */
  DefaultValue: ScalarType;
  /**
   * The value associated with the preference when the toggle switch is in the ON position. The value type for this key can be any scalar type, including `boolean`, `string`, `number`, `Date`, or Data. If this key is not present, the default value type is a `boolean` with the value `true`.
   */
  TrueValue?: ScalarType;
  /**
   * The value associated with the preference when the toggle switch is in the OFF position. The value type for this key can be any scalar type, including `boolean`, `string`, `number`, `Date`, or Data. If this key is not present, the default value type is a `boolean` with the value `false`.
   */
  FalseValue?: ScalarType;
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
export interface PSSliderSpecifier {
  Type: "PSSliderSpecifier";
  /**
   * The preference key identifying the value. This is the string you use this to retrieve the preference value from the defaults database.
   */
  Key: string;
  /**
   * The default value for the preference key. This value is returned when the specified preferences key (represented by the `Key` entry) is not present in the preferences database.
   */
  DefaultValue: number;
  /**
   * The minimum value for the slider.
   */
  MinimumValue: number;
  /**
   * The maximum value for the slider.
   */
  MaximumValue: number;
  /**
   * The image to display on the side of the slider representing the minimum value. This image should be 21 by 21 pixels.
   */
  MinimumValueImage?: string;
  /**
   * The image to display on the side of the slider representing the maximum value. This image should be 21 by 21 pixels.
   */
  MaximumValueImage?: string;
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
/**
 * This element displays a preferences row, that when tapped loads a new page of preferences. You can use this element type to build hierarchical pages of preferences. https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSChildPaneSpecifier.html#//apple_ref/doc/uid/TP40007017-SW1
 */
export interface PSChildPaneSpecifier {
  Type: "PSChildPaneSpecifier";
  /**
   * The title string displayed in the preference row. This is the string the user taps to display the next page. This string is also used as the title of the screen that is subsequently displayed.
   */
  Title: string;
  /**
   * The name of the schema file to load. (This file must be a property list file.) The string you specify for this key should not contain path information or the .plist filename extension of your schema file. The Settings app looks in the top-level of your settings bundle for a .plist file with the specified name. For example, if you had a MyPrefs.plist file, you would assign the value MyPrefs to this key.
   */
  File: string;
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
export interface PSTitleValueSpecifier {
  Type: "PSTitleValueSpecifier";
  /**
   * The string displayed to the left of the value.
   */
  Title: string;
  /**
   * The preference key identifying the value. This is the string you use this to retrieve the preference value from the defaults database.
   */
  Key: string;
  /**
   * The default value for the preference key. This value is returned when the specified preferences key (represented by the `Key` entry) is not present in the preferences database.
   */
  DefaultValue: string;
  /**
   * An array of the values that could be associated with the preference key (`Key` entry) in the defaults database. These values can be of any type. Each value should have a corresponding value in the `Titles` array.
   */
  Values?: string[];
  /**
   * An array of strings that represent user-readable versions of the values in the `Values` array. The values in this array are localizable.
   */
  Titles?: string[];
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
/**
 * When the user taps a preference containing a multi-value element, the Settings app displays a new page with the possible values to choose from. Upon selecting a value, the user is returned to the previous page, and the selected value is displayed in the preference row. https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSMultiValueSpecifier.html#//apple_ref/doc/uid/TP40007016-SW1
 */
export interface PSMultiValueSpecifier {
  Type: "PSMultiValueSpecifier";
  /**
   * The user-readable string identifying the preference.
   */
  Title: string;
  /**
   * The preference key with which to associate the value. This is the string you use this to retrieve the preference value in your code.
   */
  Key: string;
  /**
   * The default value for the preference key. This value is returned when the specified preferences key (represented by the `Key` entry) is not present in the preferences database.
   */
  DefaultValue: ScalarType;
  /**
   * An array of the values that could be associated with the preference key (`Key` entry) in the defaults database. These values can be of any type. Each value should have a corresponding value in the `Titles` array.
   */
  Values: ScalarType[];
  /**
   * An array of strings that represent user-readable versions of the values in the `Values` array. These are the strings that are actually displayed on the selection page. When a string is selected, the value at the matching index is stored in the defaults database.
   */
  Titles: string[];
  /**
   * An array of strings that are abbreviated versions of the strings in the `Titles` array. When this key is included, the preference row uses the strings in the corresponding array instead of the strings in the `Titles` array. (The preference row shows the title of the preference and the currently selected value.) The longer strings in the `Titles` array are still displayed in the new page presented to the user.
   */
  ShortTitles?: string[];
  /**
   * If `true`, the values are displayed in the localized sort order of the `Titles` array.
   */
  DisplaySortedByTitle?: boolean;
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
/**
 * This type defines a radio group element, which provides two or more choices of which only one at a time can be selected. https://developer.apple.com/library/archive/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/RadioGroupElement.html#//apple_ref/doc/uid/TP30915196-SW2
 */
export interface PSRadioGroupSpecifier {
  Type: "PSRadioGroupSpecifier";
  /**
   * The title of the group. If you do not specify this key, a gap is inserted between preferences.
   */
  Title?: string;
  /**
   * The preference key with which to associate the value. This is the string you use to retrieve the preference value in your code.
   */
  Key: string;
  /**
   * Additional text to display below the group box. Providing a footer is optional. The value of this key is localizable.
   */
  FooterText?: string;
  /**
   * The default value for the preference key. This value is returned when the specified preferences key (represented by the `Key` entry) is not present in the preferences database.
   */
  DefaultValue: string;
  /**
   * An array of the values that could be associated with the preference key (`Key` entry) in the defaults database. These values can be of any type. Each value should have a corresponding value in the `Titles` array.
   */
  Values: string[];
  /**
   * An array of strings that represent user-readable versions of the values in the `Values` array. These are the strings that are actually displayed on the selection page. When a string is selected, the value at the matching index is stored in the defaults database.
   */
  Titles: string[];
  /**
   * If `true`, the values are displayed in the localized sort order of the `Titles` array.
   */
  DisplaySortedByTitle?: boolean;
  /**
   * Indicates that the element is displayed only on specific types of devices. The value of this key is an array of strings with the supported idioms. Include the string “Phone” to display the element on iPhone and iPod touch. Include the string to “Pad” to display it on iPad.
   */
  SupportedUserInterfaceIdioms?: UserInterfaceIdiom[];
}
