import plist from "@expo/plist";
import {
  ConfigPlugin,
  IOSConfig,
  withDangerousMod,
  withFinalizedMod,
  withInfoPlist,
} from "expo/config-plugins";
import fs from "fs";
import path from "path";

export type ExpoUIScenePluginOptions = {
  enabled?: boolean;
};

const PLUGIN_NAME = "expo-uiscene-lifecycle";
const GENERATED_DIRECTORY_NAME = "ExpoUIScene";
const GENERATED_SOURCE_NAME = "ExpoUIScene.swift";
const GENERATED_MARKER = "// Generated by expo-uiscene-lifecycle. Do not edit.";
const FACTORY_CLASS_NAME = "ExpoUISceneReactNativeFactory";
const SCENE_DELEGATE_CLASS_NAME = "ExpoUISceneSceneDelegate";

const ORIGINAL_APP_DELEGATE_DECLARATION =
  "class AppDelegate: ExpoAppDelegate {";
const OWNED_APP_DELEGATE_DECLARATION =
  "class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {";
const ORIGINAL_FACTORY_INITIALIZER =
  "let factory = ExpoReactNativeFactory(delegate: delegate)";
const OWNED_FACTORY_INITIALIZER = `let factory = ${FACTORY_CLASS_NAME}(delegate: delegate)`;

const SCENE_MANIFEST = {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: "Default Configuration",
        UISceneDelegateClassName: `$(PRODUCT_MODULE_NAME).${SCENE_DELEGATE_CLASS_NAME}`,
      },
    ],
  },
};

type OwnershipState = {
  ownedAtStart: boolean;
};

function assertSdk57(sdkVersion: string | undefined): void {
  if (!sdkVersion || !/^57(?:\.|$)/.test(sdkVersion)) {
    throw new Error(
      `${PLUGIN_NAME} is experimental and supports Expo SDK 57 only (received ${JSON.stringify(
        sdkVersion ?? "unknown",
      )}).`,
    );
  }
}

function countOccurrences(contents: string, value: string): number {
  return contents.split(value).length - 1;
}

function generatedPaths(projectRoot: string) {
  const sourceRoot = IOSConfig.Paths.getSourceRoot(projectRoot);
  const generatedDirectory = path.join(sourceRoot, GENERATED_DIRECTORY_NAME);
  return {
    generatedDirectory,
    generatedSource: path.join(generatedDirectory, GENERATED_SOURCE_NAME),
  };
}

function hasOwnedGeneratedSource(projectRoot: string): boolean {
  const { generatedSource } = generatedPaths(projectRoot);
  return (
    fs.existsSync(generatedSource) &&
    fs.readFileSync(generatedSource, "utf8").startsWith(GENERATED_MARKER)
  );
}

function tryHasOwnedGeneratedSource(projectRoot: string | undefined): boolean {
  if (!projectRoot) {
    return false;
  }
  try {
    return hasOwnedGeneratedSource(projectRoot);
  } catch {
    return false;
  }
}

function stripSwiftComments(contents: string): string {
  return contents.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
}

function assertSupportedAppDelegate(language: string, contents: string): void {
  if (language !== "swift") {
    throw new Error(
      `${PLUGIN_NAME} requires the standard SDK 57 Swift AppDelegate; Objective-C AppDelegates are not supported.`,
    );
  }

  const code = stripSwiftComments(contents);
  const hasOriginalDeclaration = code.includes(
    ORIGINAL_APP_DELEGATE_DECLARATION,
  );
  const hasOwnedDeclaration = code.includes(OWNED_APP_DELEGATE_DECLARATION);
  const hasOriginalFactory = code.includes(ORIGINAL_FACTORY_INITIALIZER);
  const hasOwnedFactory = code.includes(OWNED_FACTORY_INITIALIZER);
  const factoryInitializer = hasOwnedFactory
    ? OWNED_FACTORY_INITIALIZER
    : ORIGINAL_FACTORY_INITIALIZER;
  const factoryIndex = code.indexOf(factoryInitializer);
  const delegateAssignmentIndex = code.indexOf(
    "reactNativeDelegate = delegate",
    factoryIndex,
  );
  const factoryAssignmentIndex = code.indexOf(
    "reactNativeFactory = factory",
    delegateAssignmentIndex,
  );
  const windowAssignmentIndex = code.indexOf(
    "window = UIWindow(frame: UIScreen.main.bounds)",
    factoryAssignmentIndex,
  );
  const startupIndex = code.indexOf(
    "factory.startReactNative(",
    windowAssignmentIndex,
  );
  const hasStandardStartupCall =
    /factory\.startReactNative\s*\(\s*withModuleName:\s*"main"\s*,\s*in:\s*window\s*,\s*launchOptions:\s*launchOptions\s*\)/m.test(
      code,
    );
  const hasRequiredTemplateShape =
    code.includes("var window: UIWindow?") &&
    code.includes("var reactNativeFactory: RCTReactNativeFactory?") &&
    factoryIndex >= 0 &&
    delegateAssignmentIndex > factoryIndex &&
    factoryAssignmentIndex > delegateAssignmentIndex &&
    windowAssignmentIndex > factoryAssignmentIndex &&
    startupIndex > windowAssignmentIndex &&
    hasStandardStartupCall;

  if (
    (!hasOriginalDeclaration && !hasOwnedDeclaration) ||
    (!hasOriginalFactory && !hasOwnedFactory) ||
    !hasRequiredTemplateShape
  ) {
    throw new Error(
      `${PLUGIN_NAME} could not recognize the AppDelegate shape. Only the standard Expo SDK 57 Swift template is supported.`,
    );
  }

  if (
    countOccurrences(
      contents,
      hasOwnedDeclaration
        ? OWNED_APP_DELEGATE_DECLARATION
        : ORIGINAL_APP_DELEGATE_DECLARATION,
    ) !== 1 ||
    countOccurrences(
      contents,
      hasOwnedFactory
        ? OWNED_FACTORY_INITIALIZER
        : ORIGINAL_FACTORY_INITIALIZER,
    ) !== 1
  ) {
    throw new Error(
      `${PLUGIN_NAME} could not safely update the AppDelegate shape because a required template anchor is ambiguous.`,
    );
  }
}

function restoreOwnedAppDelegate(contents: string): string {
  const restoredContents = contents
    .replace(OWNED_APP_DELEGATE_DECLARATION, ORIGINAL_APP_DELEGATE_DECLARATION)
    .replace(OWNED_FACTORY_INITIALIZER, ORIGINAL_FACTORY_INITIALIZER);
  if (
    restoredContents.includes("ExpoReactNativeFactoryProvider") ||
    restoredContents.includes(FACTORY_CLASS_NAME)
  ) {
    throw new Error(
      `${PLUGIN_NAME} cannot disable because the AppDelegate generated anchors were edited. Restore the generated AppDelegate declaration and factory initializer before disabling.`,
    );
  }
  return restoredContents;
}

function isOwnedManifest(value: unknown): boolean {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }
  const record = value as Record<string, unknown>;
  const expected = SCENE_MANIFEST as Record<string, unknown>;
  const keys = Object.keys(record);
  const expectedKeys = Object.keys(expected);
  return (
    keys.length === expectedKeys.length &&
    expectedKeys.every((key) => {
      const actualValue = record[key];
      const expectedValue = expected[key];
      if (Array.isArray(expectedValue)) {
        return (
          Array.isArray(actualValue) &&
          actualValue.length === expectedValue.length &&
          actualValue.every((item, index) =>
            isStructurallyEqual(item, expectedValue[index]),
          )
        );
      }
      return isStructurallyEqual(actualValue, expectedValue);
    })
  );
}

function isStructurallyEqual(actual: unknown, expected: unknown): boolean {
  if (Array.isArray(expected)) {
    return (
      Array.isArray(actual) &&
      actual.length === expected.length &&
      actual.every((item, index) => isStructurallyEqual(item, expected[index]))
    );
  }
  if (expected !== null && typeof expected === "object") {
    if (
      actual === null ||
      typeof actual !== "object" ||
      Array.isArray(actual)
    ) {
      return false;
    }
    const actualRecord = actual as Record<string, unknown>;
    const expectedRecord = expected as Record<string, unknown>;
    const expectedKeys = Object.keys(expectedRecord);
    return (
      Object.keys(actualRecord).length === expectedKeys.length &&
      expectedKeys.every((key) =>
        isStructurallyEqual(actualRecord[key], expectedRecord[key]),
      )
    );
  }
  return actual === expected;
}

function manifestReferencesOwnedDelegate(value: unknown): boolean {
  if (Array.isArray(value)) {
    return value.some(manifestReferencesOwnedDelegate);
  }
  if (value !== null && typeof value === "object") {
    return Object.values(value).some(manifestReferencesOwnedDelegate);
  }
  return (
    typeof value === "string" &&
    (value === SCENE_DELEGATE_CLASS_NAME ||
      value.endsWith(`.${SCENE_DELEGATE_CLASS_NAME}`))
  );
}

function getApplicationTarget(project: any): { id: string; target: any } {
  const objects = project.hash.project.objects;
  const targets = project
    .getFirstProject()
    .firstProject.targets.map(({ value }: { value: string }) => ({
      id: value,
      target: objects.PBXNativeTarget[value],
    }))
    .filter(
      ({ target }: { target: any }) =>
        target?.productType?.replace(/^"|"$/g, "") ===
        "com.apple.product-type.application",
    );

  if (targets.length !== 1) {
    throw new Error(
      `${PLUGIN_NAME} expected exactly one iOS application target, but found ${targets.length}.`,
    );
  }
  return targets[0];
}

function getApplicationInfoPlistPaths(
  projectRoot: string,
  project: any,
): string[] {
  const { target } = getApplicationTarget(project);
  const objects = project.hash.project.objects;
  const configurationList =
    objects.XCConfigurationList[target.buildConfigurationList];
  const paths = configurationList?.buildConfigurations.map(
    ({ value: configurationId, comment: configurationComment }: any) => {
      const buildConfiguration = objects.XCBuildConfiguration[configurationId];
      const configurationName =
        buildConfiguration?.name?.replace(/^"|"$/g, "") ??
        configurationComment ??
        configurationId;
      const infoPlistBuildProperty =
        buildConfiguration?.buildSettings?.INFOPLIST_FILE;
      if (typeof infoPlistBuildProperty !== "string") {
        throw new Error(
          `${PLUGIN_NAME} could not resolve the application target's INFOPLIST_FILE build setting for ${configurationName}.`,
        );
      }

      const relativeInfoPlistPath = infoPlistBuildProperty
        .replace(/"/g, "")
        .replace("$(SRCROOT)", "");
      const infoPlistPath = path.join(
        projectRoot,
        "ios",
        relativeInfoPlistPath,
      );
      if (!fs.existsSync(infoPlistPath)) {
        throw new Error(
          `${PLUGIN_NAME} could not find the application target's ${configurationName} Info.plist at ${infoPlistPath}.`,
        );
      }
      return infoPlistPath;
    },
  );
  if (!paths?.length) {
    throw new Error(
      `${PLUGIN_NAME} could not resolve any build configurations for the application target.`,
    );
  }
  return [...new Set<string>(paths)];
}

function projectContainsFile(project: any, relativePath: string): boolean {
  const normalizedPath = relativePath.replaceAll("\\", "/");
  return Object.values(project.hash.project.objects.PBXFileReference).some(
    (file: any) =>
      file &&
      typeof file === "object" &&
      file.path?.replace(/^"|"$/g, "").replaceAll("\\", "/") === normalizedPath,
  );
}

function generatedSwiftSource(): string {
  return `${GENERATED_MARKER}

internal import Expo
import React
import UIKit

// SDK 57 does not expose Expo's later scene-lifecycle helper types. These app-local types use
// only the Expo and React Native APIs shipped by SDK 57.
protocol ExpoReactNativeFactoryProvider: AnyObject {
  var window: UIWindow? { get set }
  var reactNativeFactory: RCTReactNativeFactory? { get }
}

private struct ExpoUISceneStartRequest {
  let moduleName: String
  let initialProperties: [AnyHashable: Any]?
  let launchOptions: [AnyHashable: Any]?
}

final class ${FACTORY_CLASS_NAME}: RCTReactNativeFactory {
  private let expoFactory: ExpoReactNativeFactory
  private var startRequest: ExpoUISceneStartRequest?

  override init(delegate: any RCTReactNativeFactoryDelegate) {
    expoFactory = ExpoReactNativeFactory(delegate: delegate)
    let releaseLevel = (Bundle.main.object(forInfoDictionaryKey: "ReactNativeReleaseLevel") as? String)
      .flatMap { [
        "canary": RCTReleaseLevel.Canary,
        "experimental": RCTReleaseLevel.Experimental,
        "stable": RCTReleaseLevel.Stable,
      ][$0.lowercased()] }
      ?? RCTReleaseLevel.Stable
    super.init(delegate: delegate, releaseLevel: releaseLevel)

    // Keep callers that inspect the AppDelegate's RCTReactNativeFactory on Expo's configured
    // root-view factory. Actual starts are forwarded to expoFactory below.
    rootViewFactory = expoFactory.rootViewFactory
  }

  override func startReactNative(
    withModuleName moduleName: String,
    in window: UIWindow?,
    initialProperties: [AnyHashable: Any]?,
    launchOptions: [AnyHashable: Any]?
  ) {
    if Self.declaresSceneLifecycle && window?.windowScene == nil {
      startRequest = ExpoUISceneStartRequest(
        moduleName: moduleName,
        initialProperties: initialProperties,
        launchOptions: launchOptions
      )
      return
    }

    expoFactory.startReactNative(
      withModuleName: moduleName,
      in: window,
      initialProperties: initialProperties,
      launchOptions: launchOptions
    )
  }

  func connect(to window: UIWindow, options: UIScene.ConnectionOptions) {
    guard let request = startRequest else {
      fatalError("expo-uiscene-lifecycle could not find the React Native start deferred by AppDelegate.")
    }

    var launchOptions = request.launchOptions ?? [:]
    for (key, value) in Self.launchOptions(from: options) ?? [:] {
      launchOptions[key] = value
    }

    expoFactory.startReactNative(
      withModuleName: request.moduleName,
      in: window,
      initialProperties: request.initialProperties,
      launchOptions: launchOptions.isEmpty ? nil : launchOptions
    )
  }

  private static var declaresSceneLifecycle: Bool {
    return Bundle.main.object(forInfoDictionaryKey: "UIApplicationSceneManifest") != nil
  }

  private static func launchOptions(
    from connectionOptions: UIScene.ConnectionOptions
  ) -> [AnyHashable: Any]? {
    var launchOptions: [AnyHashable: Any] = [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[AnyHashable(UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey"))] = url
    }
    if let userActivity = connectionOptions.userActivities.first(where: {
      $0.activityType == NSUserActivityTypeBrowsingWeb
    }) {
      launchOptions[
        AnyHashable(
          UIApplication.LaunchOptionsKey(
            rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey"
          )
        )
      ] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }
    return launchOptions.isEmpty ? nil : launchOptions
  }
}

@objc(${SCENE_DELEGATE_CLASS_NAME})
final class ${SCENE_DELEGATE_CLASS_NAME}: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
      let provider = UIApplication.shared.delegate as? ExpoReactNativeFactoryProvider,
      let factory = provider.reactNativeFactory as? ${FACTORY_CLASS_NAME} else {
      fatalError("expo-uiscene-lifecycle requires its generated factory and the standard SDK 57 AppDelegate.")
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    provider.window = window
    factory.connect(to: window, options: connectionOptions)

    connectionOptions.urlContexts.forEach { context in
      _ = appDelegate?.application(
        UIApplication.shared,
        open: context.url,
        options: Self.openURLOptions(from: context.options)
      )
    }
    connectionOptions.userActivities.forEach { activity in
      _ = appDelegate?.application(
        UIApplication.shared,
        continue: activity,
        restorationHandler: { _ in }
      )
    }
    if let shortcutItem = connectionOptions.shortcutItem,
      let appDelegate = appDelegate {
      appDelegate.application(
        UIApplication.shared,
        performActionFor: shortcutItem,
        completionHandler: { _ in }
      )
    }
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    URLContexts.forEach { context in
      _ = appDelegate?.application(
        UIApplication.shared,
        open: context.url,
        options: Self.openURLOptions(from: context.options)
      )
    }
  }

  func scene(_ scene: UIScene, willContinueUserActivityWithType userActivityType: String) {
    _ = appDelegate?.application(
      UIApplication.shared,
      willContinueUserActivityWithType: userActivityType
    )
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = appDelegate?.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }

  func scene(
    _ scene: UIScene,
    didFailToContinueUserActivityWithType userActivityType: String,
    error: Error
  ) {
    appDelegate?.application(
      UIApplication.shared,
      didFailToContinueUserActivityWithType: userActivityType,
      error: error
    )
  }

  func scene(_ scene: UIScene, didUpdate userActivity: NSUserActivity) {
    appDelegate?.application(UIApplication.shared, didUpdate: userActivity)
  }

  func windowScene(
    _ windowScene: UIWindowScene,
    performActionFor shortcutItem: UIApplicationShortcutItem,
    completionHandler: @escaping (Bool) -> Void
  ) {
    guard let appDelegate else {
      completionHandler(false)
      return
    }
    appDelegate.application(
      UIApplication.shared,
      performActionFor: shortcutItem,
      completionHandler: completionHandler
    )
  }

  private var appDelegate: ExpoAppDelegate? {
    return UIApplication.shared.delegate as? ExpoAppDelegate
  }

  private static func openURLOptions(
    from sceneOptions: UIScene.OpenURLOptions
  ) -> [UIApplication.OpenURLOptionsKey: Any] {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [
      .openInPlace: sceneOptions.openInPlace,
    ]
    if let sourceApplication = sceneOptions.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = sceneOptions.annotation {
      options[.annotation] = annotation
    }
    return options
  }
}
`;
}

const withExpoUIScene: ConfigPlugin<ExpoUIScenePluginOptions | void> = (
  config,
  options,
) => {
  assertSdk57(config.sdkVersion);
  const enabled = options?.enabled !== false;
  const configuredProjectRoot = config._internal?.projectRoot;
  const ownership: OwnershipState = {
    ownedAtStart: tryHasOwnedGeneratedSource(configuredProjectRoot),
  };

  config = withDangerousMod(config, [
    "ios",
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const appDelegate = IOSConfig.Paths.getAppDelegate(projectRoot);
      ownership.ownedAtStart = hasOwnedGeneratedSource(projectRoot);

      if (enabled) {
        assertSupportedAppDelegate(appDelegate.language, appDelegate.contents);
        const project = IOSConfig.XcodeUtils.getPbxproj(projectRoot);
        const infoPlistPaths = getApplicationInfoPlistPaths(
          projectRoot,
          project,
        );
        const infoPlistPath = infoPlistPaths[0]!;
        const infoPlist = plist.parse(fs.readFileSync(infoPlistPath, "utf8"));
        const configuredManifest =
          config.ios?.infoPlist?.UIApplicationSceneManifest;
        const effectiveManifest =
          configuredManifest !== undefined
            ? configuredManifest
            : infoPlist.UIApplicationSceneManifest;
        if (!project.findPBXGroupKey({ name: config.modRequest.projectName })) {
          throw new Error(
            `${PLUGIN_NAME} could not find the ${config.modRequest.projectName} Xcode group.`,
          );
        }
        if (
          effectiveManifest !== undefined &&
          !(ownership.ownedAtStart && isOwnedManifest(effectiveManifest))
        ) {
          throw new Error(
            `${PLUGIN_NAME} cannot enable because UIApplicationSceneManifest is already declared by the app.`,
          );
        }

        const { generatedSource } = generatedPaths(projectRoot);
        if (fs.existsSync(generatedSource) && !ownership.ownedAtStart) {
          throw new Error(
            `${PLUGIN_NAME} cannot enable because the generated source path already exists and is not plugin-owned: ${generatedSource}`,
          );
        }
      } else if (ownership.ownedAtStart) {
        restoreOwnedAppDelegate(appDelegate.contents);
      }
      return config;
    },
  ]);

  if (enabled || ownership.ownedAtStart || !configuredProjectRoot) {
    config = withInfoPlist(config, (config) => {
      const manifest = config.modResults.UIApplicationSceneManifest;
      if (enabled) {
        if (
          manifest !== undefined &&
          !(ownership.ownedAtStart && isOwnedManifest(manifest))
        ) {
          throw new Error(
            `${PLUGIN_NAME} cannot enable because UIApplicationSceneManifest is already declared by the app.`,
          );
        }
        config.modResults.UIApplicationSceneManifest =
          structuredClone(SCENE_MANIFEST);
      } else if (ownership.ownedAtStart && isOwnedManifest(manifest)) {
        delete config.modResults.UIApplicationSceneManifest;
      }
      return config;
    });
  }

  if (enabled) {
    config = withFinalizedMod(config, [
      "ios",
      async (config) => {
        const projectRoot = config.modRequest.projectRoot;
        const projectName = config.modRequest.projectName;
        const project = IOSConfig.XcodeUtils.getPbxproj(projectRoot);
        for (const infoPlistPath of getApplicationInfoPlistPaths(
          projectRoot,
          project,
        )) {
          const infoPlist = plist.parse(fs.readFileSync(infoPlistPath, "utf8"));
          if (!isOwnedManifest(infoPlist.UIApplicationSceneManifest)) {
            throw new Error(
              `${PLUGIN_NAME} cannot enable because the final UIApplicationSceneManifest in ${infoPlistPath} is not plugin-owned.`,
            );
          }
        }

        const appDelegate = IOSConfig.Paths.getAppDelegate(projectRoot);
        assertSupportedAppDelegate(appDelegate.language, appDelegate.contents);
        const appDelegateContents = appDelegate.contents
          .replace(
            ORIGINAL_APP_DELEGATE_DECLARATION,
            OWNED_APP_DELEGATE_DECLARATION,
          )
          .replace(ORIGINAL_FACTORY_INITIALIZER, OWNED_FACTORY_INITIALIZER);
        const relativeSourcePath = `${projectName}/${GENERATED_DIRECTORY_NAME}/${GENERATED_SOURCE_NAME}`;
        const groupId = project.findPBXGroupKey({ name: projectName });
        if (!groupId) {
          throw new Error(
            `${PLUGIN_NAME} could not find the ${projectName} Xcode group.`,
          );
        }
        const { id: targetId } = getApplicationTarget(project);
        if (!projectContainsFile(project, relativeSourcePath)) {
          project.addSourceFile(
            relativeSourcePath,
            { target: targetId },
            groupId,
          );
        }

        const { generatedDirectory, generatedSource } =
          generatedPaths(projectRoot);
        fs.mkdirSync(generatedDirectory, { recursive: true });
        fs.writeFileSync(generatedSource, generatedSwiftSource());
        fs.writeFileSync(appDelegate.path, appDelegateContents);
        fs.writeFileSync(
          IOSConfig.Paths.getPBXProjectPath(projectRoot),
          project.writeSync(),
        );
        return config;
      },
    ]);
  }

  if (!enabled && (ownership.ownedAtStart || !configuredProjectRoot)) {
    config = withFinalizedMod(config, [
      "ios",
      async (config) => {
        if (!ownership.ownedAtStart) {
          return config;
        }

        const projectRoot = config.modRequest.projectRoot;
        const projectName = config.modRequest.projectName;
        const project = IOSConfig.XcodeUtils.getPbxproj(projectRoot);
        for (const infoPlistPath of getApplicationInfoPlistPaths(
          projectRoot,
          project,
        )) {
          const infoPlist = plist.parse(fs.readFileSync(infoPlistPath, "utf8"));
          if (
            manifestReferencesOwnedDelegate(
              infoPlist.UIApplicationSceneManifest,
            )
          ) {
            throw new Error(
              `${PLUGIN_NAME} cannot disable because ${infoPlistPath} contains a modified plugin-owned UIApplicationSceneManifest that still references the generated scene delegate. Restore the generated manifest before disabling.`,
            );
          }
        }

        const appDelegate = IOSConfig.Paths.getAppDelegate(projectRoot);
        const appDelegateContents = restoreOwnedAppDelegate(
          appDelegate.contents,
        );
        const relativeSourcePath = `${projectName}/${GENERATED_DIRECTORY_NAME}/${GENERATED_SOURCE_NAME}`;
        const groupId = project.findPBXGroupKey({ name: projectName });
        if (!groupId) {
          throw new Error(
            `${PLUGIN_NAME} could not find the ${projectName} Xcode group.`,
          );
        }
        const { id: targetId } = getApplicationTarget(project);
        if (projectContainsFile(project, relativeSourcePath)) {
          project.removeSourceFile(
            relativeSourcePath,
            { target: targetId },
            groupId,
          );
        }

        fs.writeFileSync(appDelegate.path, appDelegateContents);
        fs.writeFileSync(
          IOSConfig.Paths.getPBXProjectPath(projectRoot),
          project.writeSync(),
        );
        const { generatedDirectory, generatedSource } =
          generatedPaths(projectRoot);
        fs.unlinkSync(generatedSource);
        if (fs.readdirSync(generatedDirectory).length === 0) {
          fs.rmdirSync(generatedDirectory);
        }
        return config;
      },
    ]);
  }

  return config;
};

export default withExpoUIScene;
