import { mergeContents } from "@expo/config-plugins/build/utils/generateCode";
import {
  type ConfigPlugin,
  createRunOncePlugin,
  IOSConfig,
  withAppDelegate,
  withDangerousMod,
  withMainApplication,
  withXcodeProject,
} from "expo/config-plugins";
import fs from "fs";
import { globSync } from "glob";
import path from "path";

const pkg = {
  name: "react-native-feature-flags",
  version: "UNVERSIONED",
};

type Props = {
  nativeFlagOverrides: Record<string, boolean>;
};

// #region iOS helpers (exported for tests)

export function generateFeatureFlagOverrideHeaderIOS(): string {
  return [
    "// This file is generated by @config-plugins/react-native-feature-flags.",
    "// Do not edit manually.",
    "",
    "#ifndef RNFeatureFlagsOverride_h",
    "#define RNFeatureFlagsOverride_h",
    "",
    "#ifdef __cplusplus",
    'extern "C" {',
    "#endif",
    "",
    "void RNFeatureFlagsOverride_apply(void);",
    "",
    "#ifdef __cplusplus",
    "}",
    "#endif",
    "",
    "#endif",
    "",
  ].join("\n");
}

export function generateFeatureFlagOverrideSourceIOS(
  nativeFlagOverrides: Record<string, boolean>,
): string {
  const methods = Object.entries(nativeFlagOverrides)
    .map(([flag, value]) => `  bool ${flag}() override { return ${value}; }`)
    .join("\n");

  return [
    "// This file is generated by @config-plugins/react-native-feature-flags.",
    "// Do not edit manually.",
    "",
    "#import <react/featureflags/ReactNativeFeatureFlags.h>",
    "#import <react/featureflags/ReactNativeFeatureFlagsOverridesOSSStable.h>",
    "",
    "class RNFeatureFlagsOverrideProvider : public facebook::react::ReactNativeFeatureFlagsOverridesOSSStable {",
    " public:",
    methods,
    "};",
    "",
    'extern "C" void RNFeatureFlagsOverride_apply() {',
    "  facebook::react::ReactNativeFeatureFlags::dangerouslyForceOverride(",
    "    std::make_unique<RNFeatureFlagsOverrideProvider>());",
    "}",
    "",
  ].join("\n");
}

export function addSwiftFeatureFlagOverrideCall(src: string): string {
  return mergeContents({
    tag: "rn-feature-flags-override",
    src,
    newSrc: "    RNFeatureFlagsOverride_apply()",
    anchor: /reactNativeFactory = factory/,
    offset: 1,
    comment: "//",
  }).contents;
}

// #endregion
// #region Android helpers (exported for tests)

export function addMainApplicationFeatureFlagOverrides(
  src: string,
  nativeFlagOverrides: Record<string, boolean>,
): string {
  let contents = mergeContents({
    tag: "rn-feature-flags-import",
    src,
    newSrc: [
      "import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags",
      "import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlagsDefaults",
    ].join("\n"),
    anchor: /^import/m,
    offset: 0,
    comment: "//",
  }).contents;

  const methods = Object.entries(nativeFlagOverrides)
    .map(([flag, value]) => `      override fun ${flag}(): Boolean = ${value}`)
    .join("\n");

  contents = mergeContents({
    tag: "rn-feature-flags-override",
    src: contents,
    newSrc: [
      "    ReactNativeFeatureFlags.dangerouslyForceOverride(object : ReactNativeNewArchitectureFeatureFlagsDefaults() {",
      methods,
      "    })",
    ].join("\n"),
    anchor: /loadReactNative\(this\)/,
    offset: 1,
    comment: "//",
  }).contents;

  return contents;
}

// #endregion
// #region Config plugin

const withReactNativeFeatureFlagsIOS: ConfigPlugin<Props> = (
  config,
  { nativeFlagOverrides },
) => {
  // 1. Write .h, .mm files and update bridging header
  withDangerousMod(config, [
    "ios",
    async (config) => {
      const projectDir = path.join(
        config.modRequest.platformProjectRoot,
        config.modRequest.projectName!,
      );

      fs.writeFileSync(
        path.join(projectDir, "RNFeatureFlagsOverride.h"),
        generateFeatureFlagOverrideHeaderIOS(),
      );
      fs.writeFileSync(
        path.join(projectDir, "RNFeatureFlagsOverride.mm"),
        generateFeatureFlagOverrideSourceIOS(nativeFlagOverrides),
      );

      // Append #import to bridging header
      const [bridgingHeader] = globSync("*-Bridging-Header.h", {
        absolute: true,
        cwd: projectDir,
      });

      if (!bridgingHeader) {
        throw new Error(
          `${pkg.name}: Cannot find bridging header. Please make sure your project has a *-Bridging-Header.h file.`,
        );
      }

      const src = fs.readFileSync(bridgingHeader, "utf-8");
      const result = mergeContents({
        tag: "rn-feature-flags-import",
        src,
        newSrc: '#import "RNFeatureFlagsOverride.h"',
        anchor: /\/\//,
        offset: 4,
        comment: "//",
      });
      fs.writeFileSync(bridgingHeader, result.contents, "utf-8");

      return config;
    },
  ]);

  // 2. Add files to Xcode project
  config = withXcodeProject(config, (config) => {
    const projectName = config.modRequest.projectName!;
    const target = IOSConfig.XcodeUtils.getApplicationNativeTarget({
      project: config.modResults,
      projectName,
    });

    config.modResults.addHeaderFile(
      `${projectName}/RNFeatureFlagsOverride.h`,
      {},
    );
    config.modResults.addSourceFile(
      `${projectName}/RNFeatureFlagsOverride.mm`,
      { target: target.uuid },
    );

    return config;
  });

  // 3. Insert Swift function call into AppDelegate
  config = withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `${pkg.name}: Only Swift AppDelegate is supported (found "${config.modResults.language}"). This plugin requires Expo SDK 53+.`,
      );
    }

    config.modResults.contents = addSwiftFeatureFlagOverrideCall(
      config.modResults.contents,
    );

    return config;
  });

  return config;
};

const withReactNativeFeatureFlagsAndroid: ConfigPlugin<Props> = (
  config,
  { nativeFlagOverrides },
) => {
  return withMainApplication(config, (config) => {
    config.modResults.contents = addMainApplicationFeatureFlagOverrides(
      config.modResults.contents,
      nativeFlagOverrides,
    );
    return config;
  });
};

/**
 * Config plugin to override ReactNativeFeatureFlags before React Native initializes.
 */
const withReactNativeFeatureFlags: ConfigPlugin<Props> = (config, props) => {
  if (
    !props?.nativeFlagOverrides ||
    typeof props.nativeFlagOverrides !== "object" ||
    Object.keys(props.nativeFlagOverrides).length === 0
  ) {
    throw new Error(
      `${pkg.name}: "nativeFlagOverrides" must be a non-empty object with boolean values.`,
    );
  }

  for (const [key, value] of Object.entries(props.nativeFlagOverrides)) {
    if (typeof value !== "boolean") {
      throw new Error(
        `${pkg.name}: "nativeFlagOverrides.${key}" must be a boolean, got ${typeof value}.`,
      );
    }
  }

  config = withReactNativeFeatureFlagsIOS(config, props);
  config = withReactNativeFeatureFlagsAndroid(config, props);

  return config;
};

// #endregion

export default createRunOncePlugin(
  withReactNativeFeatureFlags,
  pkg.name,
  pkg.version,
);
