name: Check Markdown links
on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - .github/workflows/lint-md.yml
      - "**.md"
  pull_request:
    paths:
      - .github/workflows/lint-md.yml
      - "**.md"

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx remark --use validate-links . .github
