name: Test Packages
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["20", "22"]
    name: Build and test on Node ${{ matrix.node }}
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1

      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm --filter './packages/*' run build

      - name: Lint all packages
        run: pnpm --filter './packages/*' run lint --max-warnings 0

      - name: Test all packages
        run: pnpm --filter './packages/*' run test --passWithNoTests
        env:
          CI: true
          EXPO_DEBUG: true
